version: "3.3"
services:
  mysql:
    container_name: billing_db
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
      - MYSQL_DATABASE=billing
    ports:
      - 3305:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 3s
      retries: 3