version: "3.9"
services:
  mysql:
    container_name: billing_db
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=change_me
      - MYSQL_DATABASE=billing
    ports:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    environment:
      - HTTP_ADDR=:80
      - DATABASE_CONFIG_DATA_SOURCE=root:change_me@tcp(billing_db:3306)/billing?timeout=10s&parseTime=true
    ports:
      - 8088:80
    depends_on:
      mysql:
        condition: service_healthy