// Code generated by MockGen. DO NOT EDIT.
// Source: bill.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	presenter "github.com/dchlong/billing-be/internal/presenter"
	gomock "github.com/golang/mock/gomock"
)

// MockBillService is a mock of BillService interface.
type MockBillService struct {
	ctrl     *gomock.Controller
	recorder *MockBillServiceMockRecorder
}

// MockBillServiceMockRecorder is the mock recorder for MockBillService.
type MockBillServiceMockRecorder struct {
	mock *MockBillService
}

// NewMockBillService creates a new mock instance.
func NewMockBillService(ctrl *gomock.Controller) *MockBillService {
	mock := &MockBillService{ctrl: ctrl}
	mock.recorder = &MockBillServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillService) EXPECT() *MockBillServiceMockRecorder {
	return m.recorder
}

// CreateCallHistory mocks base method.
func (m *MockBillService) CreateCallHistory(ctx context.Context, userName string, duration int64) (*presenter.CreateCallHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCallHistory", ctx, userName, duration)
	ret0, _ := ret[0].(*presenter.CreateCallHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCallHistory indicates an expected call of CreateCallHistory.
func (mr *MockBillServiceMockRecorder) CreateCallHistory(ctx, userName, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCallHistory", reflect.TypeOf((*MockBillService)(nil).CreateCallHistory), ctx, userName, duration)
}

// GetBill mocks base method.
func (m *MockBillService) GetBill(ctx context.Context, userName string) (*presenter.GetBillResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBill", ctx, userName)
	ret0, _ := ret[0].(*presenter.GetBillResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBill indicates an expected call of GetBill.
func (mr *MockBillServiceMockRecorder) GetBill(ctx, userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBill", reflect.TypeOf((*MockBillService)(nil).GetBill), ctx, userName)
}
